# Generated by Django 5.2.5 on 2025-08-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name="Ім'я:")),
                ('last_name', models.CharField(max_length=15, verbose_name='Прізвище:')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Елеткронна пошта:')),
                ('age', models.PositiveBigIntegerField(verbose_name='Вік:')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнтти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва будинуку:')),
                ('info', models.TextField(max_length=1024, verbose_name='Інформація за будинок:')),
                ('country', models.TextField(max_length=15, verbose_name='Країна:')),
                ('adress', models.CharField(max_length=100, verbose_name='Адреса будинку:')),
                ('room_count', models.PositiveIntegerField(default=0, verbose_name='Кількість кімнат:')),
                ('square', models.PositiveIntegerField(default=0, verbose_name='Площа будинку:')),
                ('price_by_day', models.PositiveSmallIntegerField(verbose_name='Ціна за добу:')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг:')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Заброньовано:')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Будинок',
                'verbose_name_plural': 'Будинки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата заїзду')),
                ('departure_day', models.DateField(verbose_name='Дата віїзду')),
                ('comment', models.CharField(max_length=100, verbose_name='Коментарі')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.client', verbose_name='Клієнт')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_all', to='booking.house', verbose_name='Будинок')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
