# Generated by Django 5.2.5 on 2025-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_house_people_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='departure_day',
            new_name='departure_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коментарі'),
        ),
    ]
